//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeDownloadUtil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubeDownloadUtil.source.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        internal static string bin {
            get {
                return ResourceManager.GetString("bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        internal static string ConfDefault {
            get {
                return ResourceManager.GetString("ConfDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTubeDownloadUtil.HTML_Renderer.Source.HtmlRenderer.Core.Utils.
        /// </summary>
        internal static string EmbeddedResNamespace {
            get {
                return ResourceManager.GetString("EmbeddedResNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /e,/select,&quot;$path$&quot;.
        /// </summary>
        internal static string ExploreToFile {
            get {
                return ResourceManager.GetString("ExploreToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /e,&quot;$path$&quot;.
        /// </summary>
        internal static string ExploreToPath {
            get {
                return ResourceManager.GetString("ExploreToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not extract the videos of a playlist, only list them..
        /// </summary>
        internal static string FlatPlaylist {
            get {
                return ResourceManager.GetString("FlatPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort on Duplicate (File Exists).
        /// </summary>
        internal static string mAbortOnDuplicate {
            get {
                return ResourceManager.GetString("mAbortOnDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MetaData.
        /// </summary>
        internal static string mAddMetadata {
            get {
                return ResourceManager.GetString("mAddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write metadata to the video file.
        /// </summary>
        internal static string mAddMetaDataTip {
            get {
                return ResourceManager.GetString("mAddMetaDataTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Unfinished Downloads.
        /// </summary>
        internal static string mContinue {
            get {
                return ResourceManager.GetString("mContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Note&gt; Here, if this is not enabled, we will use the --no-continue Flag.
        ///
        ///Force resume of partially downloaded files.
        ///By default, youtube-dl will resume downloads if possible..
        /// </summary>
        internal static string mContinueTip {
            get {
                return ResourceManager.GetString("mContinueTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Targets.
        /// </summary>
        internal static string mDownloadTargets {
            get {
                return ResourceManager.GetString("mDownloadTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Subtitles.
        /// </summary>
        internal static string mEmbedSubs {
            get {
                return ResourceManager.GetString("mEmbedSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed subtitles in the video (only for mp4, webm and mkv videos).
        /// </summary>
        internal static string mEmbedSubsTip {
            get {
                return ResourceManager.GetString("mEmbedSubsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Thumbnail.
        /// </summary>
        internal static string mEmbedThumb {
            get {
                return ResourceManager.GetString("mEmbedThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed thumbnail in the audio as cover art.
        /// </summary>
        internal static string mEmbedThumbTip {
            get {
                return ResourceManager.GetString("mEmbedThumbTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore to Target Directory.
        /// </summary>
        internal static string mExplore {
            get {
                return ResourceManager.GetString("mExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Audio.
        /// </summary>
        internal static string mExtractAudio {
            get {
                return ResourceManager.GetString("mExtractAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert video files to audio-only files (requires ffmpeg or avconv and ffprobe or avprobe).
        /// </summary>
        internal static string mExtractAudioTip {
            get {
                return ResourceManager.GetString("mExtractAudioTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Playlist.
        /// </summary>
        internal static string mFlatPlaylist {
            get {
                return ResourceManager.GetString("mFlatPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Playlist.
        /// </summary>
        internal static string mGetPlaylist {
            get {
                return ResourceManager.GetString("mGetPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the playlist, if the URL refers to a video and a playlist..
        /// </summary>
        internal static string mGetPlaylistTip {
            get {
                return ResourceManager.GetString("mGetPlaylistTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Errors.
        /// </summary>
        internal static string mIgnoreErrors {
            get {
                return ResourceManager.GetString("mIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on download errors, for example to skip unavailable videos in a playlist.
        /// </summary>
        internal static string mIgnoreErrorsTip {
            get {
                return ResourceManager.GetString("mIgnoreErrorsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Downloads.
        /// </summary>
        internal static string mMaxDownloads {
            get {
                return ResourceManager.GetString("mMaxDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort after downloading NUMBER files
        ///[Where NUMBER is set by changing the value in the tool-strip below the &apos;address-bar&apos; in the application].
        /// </summary>
        internal static string mMaxDownloadsTip {
            get {
                return ResourceManager.GetString("mMaxDownloadsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name From URL.
        /// </summary>
        internal static string mNameFromURL {
            get {
                return ResourceManager.GetString("mNameFromURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a name for output based on the navigation URL.
        /// </summary>
        internal static string mNameFromURL_Msg {
            get {
                return ResourceManager.GetString("mNameFromURL_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-dl flags.
        /// </summary>
        internal static string mOptions {
            get {
                return ResourceManager.GetString("mOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer FFmpeg.
        /// </summary>
        internal static string mPreferFFmpeg {
            get {
                return ResourceManager.GetString("mPreferFFmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer ffmpeg over avconv for running the postprocessors.
        /// </summary>
        internal static string mPreferFFmpegTip {
            get {
                return ResourceManager.GetString("mPreferFFmpegTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Target Directory.
        /// </summary>
        internal static string mRemovePath {
            get {
                return ResourceManager.GetString("mRemovePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has already been downloaded.
        /// </summary>
        internal static string msgAllreadyDownloaded {
            get {
                return ResourceManager.GetString("msgAllreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current target path was not stored to your set.
        /// </summary>
        internal static string msgCreateTsFail {
            get {
                return ResourceManager.GetString("msgCreateTsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing to remove.
        /// </summary>
        internal static string msgCreateTsFailCaption {
            get {
                return ResourceManager.GetString("msgCreateTsFailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string msgCreateTsSuccessCaption {
            get {
                return ResourceManager.GetString("msgCreateTsSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [download] Destination: .
        /// </summary>
        internal static string msgDownloadDestination {
            get {
                return ResourceManager.GetString("msgDownloadDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [download] .
        /// </summary>
        internal static string msgDownloadHeading {
            get {
                return ResourceManager.GetString("msgDownloadHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled
        ///&lt;WARNING&gt; Incomplete files likely remain
        ///.
        /// </summary>
        internal static string msgUserAbort {
            get {
                return ResourceManager.GetString("msgUserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: Shell-Folder.
        /// </summary>
        internal static string mShellFolders {
            get {
                return ResourceManager.GetString("mShellFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate.
        /// </summary>
        internal static string mSimulate {
            get {
                return ResourceManager.GetString("mSimulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not download the video and do not write anything to disk.
        /// </summary>
        internal static string mSimulateTip {
            get {
                return ResourceManager.GetString("mSimulateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Top-Level Window.
        /// </summary>
        internal static string mTopLevel {
            get {
                return ResourceManager.GetString("mTopLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the Window to stay on top of others..
        /// </summary>
        internal static string mTopLevelTip {
            get {
                return ResourceManager.GetString("mTopLevelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string mVerbose {
            get {
                return ResourceManager.GetString("mVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print various debugging information.
        /// </summary>
        internal static string mVerboseTip {
            get {
                return ResourceManager.GetString("mVerboseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write: Annotations.
        /// </summary>
        internal static string mWriteAnnotations {
            get {
                return ResourceManager.GetString("mWriteAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write: video annotations to a .annotations.xml file
        ///[youtube].
        /// </summary>
        internal static string mWriteAnnotationsTip {
            get {
                return ResourceManager.GetString("mWriteAnnotationsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write: Auto Subtitles.
        /// </summary>
        internal static string mWriteAutoSub {
            get {
                return ResourceManager.GetString("mWriteAutoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write: automatically generated subtitle file
        ///[youtube].
        /// </summary>
        internal static string mWriteAutoSubTip {
            get {
                return ResourceManager.GetString("mWriteAutoSubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write: Subtitles.
        /// </summary>
        internal static string mWriteSubs {
            get {
                return ResourceManager.GetString("mWriteSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write subtitle file.
        /// </summary>
        internal static string mWriteSubsTip {
            get {
                return ResourceManager.GetString("mWriteSubsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A helper for running youtube-dl.
        /// </summary>
        internal static string ShowHelp {
            get {
                return ResourceManager.GetString("ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/rg3/youtube-dl/master/README.md.
        /// </summary>
        internal static string uriYoutubeDlHelp {
            get {
                return ResourceManager.GetString("uriYoutubeDlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\Downloads.
        /// </summary>
        internal static string UserDownloads {
            get {
                return ResourceManager.GetString("UserDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-dl (or target executable) wasn&apos;t found.
        ///&lt;to-fix&gt; Drag-Drop youtube-dl.exe back onto the app for it to be configured properly..
        /// </summary>
        internal static string Win32Native_NoExecutable_Msg {
            get {
                return ResourceManager.GetString("Win32Native_NoExecutable_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target-directory (WorkPath) wasn&apos;t found.\n&lt;to-fix&gt; Select another target (output) path..
        /// </summary>
        internal static string Win32Native_NoWorkingDirectory_Msg {
            get {
                return ResourceManager.GetString("Win32Native_NoWorkingDirectory_Msg", resourceCulture);
            }
        }
    }
}
