//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeDownloadUtil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubeDownloadUtil.source.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not extract the videos of a playlist, only list them..
        /// </summary>
        internal static string FlatPlaylist {
            get {
                return ResourceManager.GetString("FlatPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort on Duplicate (File Exists).
        /// </summary>
        internal static string mAbortOnDuplicate {
            get {
                return ResourceManager.GetString("mAbortOnDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MetaData.
        /// </summary>
        internal static string mAddMetadata {
            get {
                return ResourceManager.GetString("mAddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Unfinished Downloads.
        /// </summary>
        internal static string mContinue {
            get {
                return ResourceManager.GetString("mContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Targets.
        /// </summary>
        internal static string mDownloadTargets {
            get {
                return ResourceManager.GetString("mDownloadTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Subtitles.
        /// </summary>
        internal static string mEmbedSubs {
            get {
                return ResourceManager.GetString("mEmbedSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Thumbnail.
        /// </summary>
        internal static string mEmbedThumb {
            get {
                return ResourceManager.GetString("mEmbedThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore to Target Directory.
        /// </summary>
        internal static string mExplore {
            get {
                return ResourceManager.GetString("mExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Playlist.
        /// </summary>
        internal static string mFlatPlaylist {
            get {
                return ResourceManager.GetString("mFlatPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Playlist.
        /// </summary>
        internal static string mGetPlaylist {
            get {
                return ResourceManager.GetString("mGetPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Errors.
        /// </summary>
        internal static string mIgnoreErrors {
            get {
                return ResourceManager.GetString("mIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-dl flags.
        /// </summary>
        internal static string mOptions {
            get {
                return ResourceManager.GetString("mOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Target Directory.
        /// </summary>
        internal static string mRemovePath {
            get {
                return ResourceManager.GetString("mRemovePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has already been downloaded.
        /// </summary>
        internal static string msgAllreadyDownloaded {
            get {
                return ResourceManager.GetString("msgAllreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current target path was not stored to your set.
        /// </summary>
        internal static string msgCreateTsFail {
            get {
                return ResourceManager.GetString("msgCreateTsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing to remove.
        /// </summary>
        internal static string msgCreateTsFailCaption {
            get {
                return ResourceManager.GetString("msgCreateTsFailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string msgCreateTsSuccessCaption {
            get {
                return ResourceManager.GetString("msgCreateTsSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [download] Destination: .
        /// </summary>
        internal static string msgDownloadDestination {
            get {
                return ResourceManager.GetString("msgDownloadDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [download] .
        /// </summary>
        internal static string msgDownloadHeading {
            get {
                return ResourceManager.GetString("msgDownloadHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: Shell-Folder.
        /// </summary>
        internal static string mShellFolders {
            get {
                return ResourceManager.GetString("mShellFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string mVerbose {
            get {
                return ResourceManager.GetString("mVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Auto Subtitles (yt: if present).
        /// </summary>
        internal static string mWriteAutoSubs {
            get {
                return ResourceManager.GetString("mWriteAutoSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Subtitles (yt: if present).
        /// </summary>
        internal static string mWriteSubs {
            get {
                return ResourceManager.GetString("mWriteSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/rg3/youtube-dl/master/README.md.
        /// </summary>
        internal static string uriYoutubeDlHelp {
            get {
                return ResourceManager.GetString("uriYoutubeDlHelp", resourceCulture);
            }
        }
    }
}
